baseURL = "https://totalemail.io/"
languageCode = "en-us"
title = "TotalEmail"
theme = "detox"

[params]
author = "TotalEmail"
description = "A blog on email analysis, spam detection, and building an email database."
